// Postbuild step: run react-snap programmatically with a dynamic route list.
// react-snap's package.json `include` is static and cannot enumerate DB-driven
// blog slugs, so we read the include[] generated by generate-blog-routes.mjs and
// merge it with the rest of the reactSnap config from package.json.

import { readFileSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const require = createRequire(import.meta.url);

const pkg = JSON.parse(readFileSync(path.join(ROOT, "package.json"), "utf8"));
const reactSnapConfig = pkg.reactSnap || {};

const routesFile = path.join(ROOT, "reactsnap-routes.json");
if (!existsSync(routesFile)) {
  console.error("[snap] reactsnap-routes.json missing — run generate-blog-routes.mjs (prebuild) first.");
  process.exit(1);
}
const include = JSON.parse(readFileSync(routesFile, "utf8"));
if (!Array.isArray(include) || include.length === 0) {
  console.error("[snap] route list is empty — refusing to prerender.");
  process.exit(1);
}

// react-snap is CommonJS; load it via require and grab its `run` export.
const reactSnap = require("react-snap");
const run = reactSnap.run || reactSnap.default?.run || reactSnap;

console.log(`[snap] prerendering ${include.length} routes...`);

run({ ...reactSnapConfig, include })
  .then(() => {
    console.log("[snap] done.");
  })
  .catch((err) => {
    console.error("[snap] FAILED:", err);
    process.exit(1);
  });
